Remove fields that conflict with rust builtins
```
   Compiling gitea v0.1.0 (/home/russell/projects/rs-gitea)
error: `self` cannot be a raw identifier
  --> /home/russell/projects/rs-gitea/./file_links_response.rs:47:12
   |
47 |     pub fn r#self(mut self, value: impl Into<String>) -> Self {
   |            ^^^^^^

error: expected identifier, found reserved keyword `do`
 --> /home/russell/projects/rs-gitea/./merge_pull_request_option.rs:6:9
  |
6 |     pub do: crate::merge_pull_request_option::MergePullRequestOptionDo,
  |         ^^ expected identifier, found reserved keyword
  |
help: you can escape reserved keywords to use them as identifiers
  |
6 |     pub r#do: crate::merge_pull_request_option::MergePullRequestOptionDo,
  |         ^^^^

error: expected identifier, found reserved keyword `do`
  --> /home/russell/projects/rs-gitea/./merge_pull_request_option.rs:68:12
   |
68 |     pub fn do(mut self, value: crate::merge_pull_request_option::MergePullRequestOptionDo) -> MergePullRequestOptionBuilder<crate::generics::DoExists> {
   |            ^^ expected identifier, found reserved keyword
   |
help: you can escape reserved keywords to use them as identifiers
   |
68 |     pub fn r#do(mut self, value: crate::merge_pull_request_option::MergePullRequestOptionDo) -> MergePullRequestOptionBuilder<crate::generics::DoExists> {
   |            ^^^^

error: expected identifier, found reserved keyword `do`
  --> /home/russell/projects/rs-gitea/./merge_pull_request_option.rs:69:19
   |
69 |         self.body.do = value.into();
   |                   ^^ expected identifier, found reserved keyword
   |
help: you can escape reserved keywords to use them as identifiers
   |
69 |         self.body.r#do = value.into();
   |                   ^^^^

error: expected identifier, found reserved keyword `do`
   --> /home/russell/projects/rs-gitea/./merge_pull_request_option.rs:128:12
    |
128 |     pub fn do(mut self, value: crate::merge_pull_request_option::MergePullRequestOptionDo) -> MergePullRequestOptionPostBuilder<Owner, Repo, Index, crate::generics::DoExists> {
    |            ^^ expected identifier, found reserved keyword
    |
help: you can escape reserved keywords to use them as identifiers
    |
128 |     pub fn r#do(mut self, value: crate::merge_pull_request_option::MergePullRequestOptionDo) -> MergePullRequestOptionPostBuilder<Owner, Repo, Index, crate::generics::DoExists> {
    |            ^^^^

error: expected identifier, found reserved keyword `do`
   --> /home/russell/projects/rs-gitea/./merge_pull_request_option.rs:129:25
    |
129 |         self.inner.body.do = value.into();
    |                         ^^ expected identifier, found reserved keyword
    |
help: you can escape reserved keywords to use them as identifiers
    |
129 |         self.inner.body.r#do = value.into();
    |                         ^^^^

error[E0277]: the trait bound `create_hook_option::CreateHookOptionType: std::default::Default` is not satisfied
  --> /home/russell/projects/rs-gitea/./create_hook_option.rs:10:5
   |
10 |     pub type_: crate::create_hook_option::CreateHookOptionType,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `create_hook_option::CreateHookOptionType`
   |
   = note: required by `std::default::Default::default`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `merge_pull_request_option::MergePullRequestOptionDo: std::default::Default` is not satisfied
 --> /home/russell/projects/rs-gitea/./merge_pull_request_option.rs:6:5
  |
6 |     pub do: crate::merge_pull_request_option::MergePullRequestOptionDo,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `merge_pull_request_option::MergePullRequestOptionDo`
  |
  = note: required by `std::default::Default::default`
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 8 previous errors

```